# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\MALAPI\dialogAnime.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAnime(object):
    def setupUi(self, DialogAnime):
        DialogAnime.setObjectName("DialogAnime")
        DialogAnime.resize(388, 340)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogAnime)
        self.buttonBox.setGeometry(QtCore.QRect(30, 300, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.labelPicture = QtWidgets.QLabel(DialogAnime)
        self.labelPicture.setGeometry(QtCore.QRect(10, 10, 112, 172))
        self.labelPicture.setText("")
        self.labelPicture.setObjectName("labelPicture")
        self.radioButtonNotWatched = QtWidgets.QRadioButton(DialogAnime)
        self.radioButtonNotWatched.setGeometry(QtCore.QRect(20, 190, 82, 17))
        self.radioButtonNotWatched.setObjectName("radioButtonNotWatched")
        self.radioButtonCompleted = QtWidgets.QRadioButton(DialogAnime)
        self.radioButtonCompleted.setGeometry(QtCore.QRect(20, 220, 82, 17))
        self.radioButtonCompleted.setObjectName("radioButtonCompleted")
        self.comboBoxScore = QtWidgets.QComboBox(DialogAnime)
        self.comboBoxScore.setGeometry(QtCore.QRect(300, 260, 69, 22))
        self.comboBoxScore.setObjectName("comboBoxScore")
        self.comboBoxScore.addItem("")
        self.comboBoxScore.addItem("")
        self.comboBoxScore.addItem("")
        self.comboBoxScore.addItem("")
        self.comboBoxScore.addItem("")
        self.comboBoxScore.addItem("")
        self.comboBoxScore.addItem("")
        self.comboBoxScore.addItem("")
        self.comboBoxScore.addItem("")
        self.comboBoxScore.addItem("")
        self.comboBoxScore.addItem("")
        self.label = QtWidgets.QLabel(DialogAnime)
        self.label.setGeometry(QtCore.QRect(250, 260, 51, 22))
        self.label.setObjectName("label")
        self.labelSynopsis = QtWidgets.QPlainTextEdit(DialogAnime)
        self.labelSynopsis.setGeometry(QtCore.QRect(130, 10, 241, 231))
        self.labelSynopsis.setObjectName("labelSynopsis")

        self.retranslateUi(DialogAnime)
        self.buttonBox.accepted.connect(DialogAnime.accept)
        self.buttonBox.rejected.connect(DialogAnime.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogAnime)

    def retranslateUi(self, DialogAnime):
        _translate = QtCore.QCoreApplication.translate
        DialogAnime.setWindowTitle(_translate("DialogAnime", "Edit"))
        self.radioButtonNotWatched.setText(_translate("DialogAnime", "Not watched"))
        self.radioButtonCompleted.setText(_translate("DialogAnime", "Completed"))
        self.comboBoxScore.setItemText(0, _translate("DialogAnime", "none"))
        self.comboBoxScore.setItemText(1, _translate("DialogAnime", "1"))
        self.comboBoxScore.setItemText(2, _translate("DialogAnime", "2"))
        self.comboBoxScore.setItemText(3, _translate("DialogAnime", "3"))
        self.comboBoxScore.setItemText(4, _translate("DialogAnime", "4"))
        self.comboBoxScore.setItemText(5, _translate("DialogAnime", "5"))
        self.comboBoxScore.setItemText(6, _translate("DialogAnime", "6"))
        self.comboBoxScore.setItemText(7, _translate("DialogAnime", "7"))
        self.comboBoxScore.setItemText(8, _translate("DialogAnime", "8"))
        self.comboBoxScore.setItemText(9, _translate("DialogAnime", "9"))
        self.comboBoxScore.setItemText(10, _translate("DialogAnime", "10"))
        self.label.setText(_translate("DialogAnime", "Score"))
